name: doc

on: push

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build doc
      run: |
        pip install sphinx
        sphinx-build -W -b html docs/ docs/build -j auto

    - name: deploy doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        force_orphan: true
